require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'frontend/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'
    - 'config/routes.rb'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false
